### ISSUE TITLE
"An unexpected error occurred"

### ISSUE THREAD

**Issue by DavidFernandes96** [Optum/kong-spec-expose#11]
Hello,

So I managed to install the plugin, created the following service:

POST request to **https://localhost:8443/admin-api/services**
with this JSON body:
```
{
    "name":"OrdersController",
    "host":"orders-microservice",
    "path":"/api/v1/orders"
}
```
**Note:** I secured Kong's Admin API by creating a loopback route, that is why you see **admin-api/** there.

Then I added the following route with this POST request:
**https://localhost:8443/admin-api/routes**
...and this JSON body:
```
{
  "name":"v1-orders",
  "protocols": ["https"],
  "methods": ["GET","POST","PUT","DELETE"],
  "paths": ["/api/v1/orders"],
  "service": {
      "id": "<ID returned on previous response>"
  }
}
```

The plugin was added to the route above and the spec URL added was http://localhost:8080/swagger/v1/swagger.json

However, when I send a GET request to https://localhost:8443/api/v1/orders/specz I receive the following error:

```
{
    "message": "An unexpected error occurred"
}
```

What am I doing wrong?

**Comment by jeremyjpj0916** [comment]
Hmm I did a test:

Fake non-existant "spec" url:

![image](https://user-images.githubusercontent.com/31913027/128197752-1860d740-8b3c-49e5-9965-400533d8d73b.png)


![image](https://user-images.githubusercontent.com/31913027/128197854-0c94b927-0a37-4575-9e2b-b1c4f33343ee.png)

![image](https://user-images.githubusercontent.com/31913027/128197916-d4d44f7a-b408-462f-a57d-5040981540f1.png)

My plugin was attached to the route resource as well.

I am running Kong 2.4.1:
```
/ $ kong version --vv
2021/08/04 14:24:38 [verbose] Kong: 2.4.1
2021/08/04 14:24:38 [debug] ngx_lua: 10019
2021/08/04 14:24:38 [debug] nginx: 1019003
2021/08/04 14:24:38 [debug] Lua: LuaJIT 2.1.0-beta3
```

What do the logs, stacktrace say in runtime Kong when the unexpected error occurs?

**Comment by DavidFernandes96** [comment]
Greetings,

@jeremyjpj0916 Thank you for the quick reply.
It turns out I was passing the wrong URL to the plugin.
With the right one I was able to see this JSON :)

<img width="335" alt="Capture" src="https://user-images.githubusercontent.com/36897055/128218327-1df2afa5-c673-471a-b25d-aa7b12480957.PNG">


Now my question is: is it possible to pass this JSON to Swagger so when I access http://myURL:8443/my/endpoint/specz I can see Swagger's UI?

**Comment by jeremyjpj0916** [comment]
I don't think Kong works as a front for exposing a UI well. So no, it can expose the contract for a swagger UI to load the definition, but it can't load the UI itself.
