### ISSUE TITLE
Swagger - upstream server address

### ISSUE THREAD

**Issue by steveseacombe** [Optum/kong-spec-expose#2]
Hi - I've exposed a swagger endpoint using the kong-spec-expose plugin, but the server address in the swagger document is still the upstream url, not the kong url. Is there a way to substutute this for the kong url? Thanks.

**Comment by jeremyjpj0916** [comment]
@steveseacombe currently it does not swap that out. PRs welcome if you have any robust ideas for how to implement. One simple way would be have users pass a config of find/replace if it sees it in the spec http body. 

Other suggestion would simply be to expose in the spec the API Providers url and the proxy url then UI tools would render a dropdown for either to be invoked.

**Comment by steveseacombe** [comment]
Thanks @jeremyjpj0916 - find/replace may be an option for me.
