### ISSUE TITLE
Specz endpoint responses unexpected error

### ISSUE THREAD

**Issue by alninoext** [Optum/kong-spec-expose#3]
Hi there,

I'm trying plugin on a docker kong instance, I've configured the plugin using the steps posted [here](https://docs.konghq.com/hub/optum/kong-spec-expose/), and I've created my endpoint by bellow command:
<pre>
curl -s -X POST http://10.200.10.1:8001/services -d name=partners -d url=http://partners:8080/partners
curl -s -X POST http://10.200.10.1:8001/services/partners/routes -d name=partRoute -d "paths[]=/partners"
curl -X POST http://10.200.10.1:8001/services/partners/plugins \
    	--data "name=kong-spec-expose"  \
    	--data "config.spec_url=http://partners:9080/api-docs"
</pre>
However, when I hit the endpoint adding /specz termination, it responses:
<pre>
curl -X GET http://10.200.10.1:8000/partners/specz
{"message":"An unexpected error occurred"}
</pre>
Partners microservice exposes its API documentation on this url: http://partners:9080/api-docs.

I'm running Kong 5.1. Kong's log just show this:
<pre>
kong        | 172.26.0.1 - - [30/Jan/2020:17:23:31 +0000] "GET /partners/specz HTTP/1.1" 500 42 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
kong        | 2020/01/30 17:28:16 [warn] 30#0: *7176 [kong] plugins.lua:164 DEPRECATED: /plugins/schema/:name endpoint is deprecated, please use /schemas/plugins/:name instead., client: 172.26.0.1, server: kong_admin, request: "GET /plugins/schema/kong-spec-expose?size=1000 HTTP/1.1", host: "localhost:8001"
</pre>
I was wondering if there is something wrong with my configuration.
Thanks

**Comment by rsbrisci** [comment]
@alninoext What version of Kong are you running?

**Comment by rsbrisci** [comment]
We've got this tested up to `1.4.3` right now

**Comment by rsbrisci** [comment]
For that `500`, you should be getting an `error`-level log somewhere in your logs. Not just a "warn"

**Comment by alninoext** [comment]
> @alninoext What version of Kong are you running?

I'm running Kong 5.1

**Comment by alninoext** [comment]
> For that `500`, you should be getting an `error`-level log somewhere in your logs. Not just a "warn"

This is true, I'll go on this later, maybe I'm missing something

**Comment by alninoext** [comment]
> For that `500`, you should be getting an `error`-level log somewhere in your logs. Not just a "warn"

Is there a way to increase logging level in Kong?

**Comment by rsbrisci** [comment]
>I'm running Kong 5.1 

The current version of Kong is 2.0, Kong 5.1 is years away :P -  try running `kong version` to check yours


>Is there a way to increase logging level in Kong?

Yes, it depends on if you're using an nginx template, or kong.conf - but https://docs.konghq.com/1.5.x/logging/ - though `error` logs should always be shown

**Comment by alninoext** [comment]
First of all, thanks @rsbrisci. 

I was able to resume this test a couple of days ago. Actually, the problem was pretty simple, the partners microservice had an incorrect forward port, it expected that requests came from 8080 port not 9080.
