### ISSUE TITLE
Not able to see the documentation

### ISSUE THREAD

**Issue by darshanasys** [Optum/kong-spec-expose#6]
Not able to invoke the plugin - Where should I see the documentation?

I have enabled the plugin on services and route, but unable to view the spec.

I am using kong 2.0 version. What am I missing?

**Comment by jeremyjpj0916** [comment]
What is your plugin definition and did you enable it on the route resource? Can you specify your route resource?

Best,
Jeremy

**Comment by darshanasys** [comment]
Hi @jeremyjpj0916 ,

Thanks for the reply.

the route path i enabled the plugin is  - routes/all/specz -  it shows not found.

I have enabled it on route. I have created a test route for get method for https://restcountries.eu/rest/v2/all - but i am not able to view the same.

in the docs - https://docs.konghq.com/hub/optum/kong-spec-expose/ - it is only mentioned to enable the plugin. But where or which URL should be used to view the documentation is not mentioned.

**Comment by jeremyjpj0916** [comment]
As stated on that page:

"
Plugin will validate the Proxy request is GET method, and will validate the proxy request ends with “/specz”. If these two requirements are met, the endpoint will return the specification of the API Service with Content-Type header identical to what the API Service exposes.
"

Your configured ```config.spec_url``` can be consumed on  https://restcountries.eu/rest/v2/all/specz based on the information you have provided me.

**Comment by darshanasys** [comment]
it is redirecting to my git spec url... is this what the plugin does?

**Comment by jeremyjpj0916** [comment]
What did you think it did? This plugin allows bypassing auth on a protected proxy to load spec documentation for a potential user, it makes an http call and loads the response data to the client calling the specz proxy url path, all the real code logic is here, simple behavior:

https://github.com/Optum/kong-spec-expose/blob/master/src/access.lua#L9
