### ISSUE TITLE
not able to install plugin

### ISSUE THREAD

**Issue by rakeshsingh13** [Optum/kong-spec-expose#9]
I have use kong version 2.0.4.
and I face the following error.

{
    "message": "schema violation (name: plugin 'kong-spec-expose' not enabled; add it to the 'plugins' configuration property)",
    "name": "schema violation",
    "fields": {
        "name": "plugin 'kong-spec-expose' not enabled; add it to the 'plugins' configuration property"
    },
    "code": 2
}

I follow the given steps in the following doc.
https://docs.konghq.com/hub/optum/kong-spec-expose/

**Comment by ckatta** [comment]
@rakeshsingh13  did you get any solution for this?

**Comment by jeremyjpj0916** [comment]
The error is being presented by Kong:

"plugin 'kong-spec-expose' not enabled; add it to the 'plugins' configuration property"

You have to add kong-spec-expose to your plugins ENV variable(KONG_PLUGINS) or in the kong config file to be able to use it.

**Comment by heman-m** [comment]
@rakeshsingh13 , is this configured locally or k8s cluster level?
